# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2283d2057a7eb3042ed3624a24240d5258ec2388448b139768bf6d8ce7469cd9c7786572dda22dd295545f7583a9b38a89d83f1e04c27d2c2358ab3ee5bc264

test:
  secret_key_base: 3b0a49f25091d19f330a314f84a91b844d31f0eb1a70f5c1e90ee09904edfda5502afa50f4ea43d4f388c7dfba0ffa62bb2875cff5c1fd2605f85a79bf58d164

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
